# Generated by Django 4.2.9 on 2024-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hjhbvj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
